version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: hospital_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ["CMD-SHELL", "pg_isready -U user"]
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
      - /app/node_modules
    # depends_on:
    #   db:
    #     condition: service_healthy
    environment:
      DATABASE_URL: postgres://user:password@db:5432/hospital_db
    entrypoint: ["/bin/sh", "-c"]
    command: ["npx prisma migrate deploy && npm run dev"]

volumes:
  postgres_data:
