# Use official Node.js 20  as the base image
FROM node:20

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Copy prisma folder early (before npm install)
COPY prisma ./prisma
COPY .env .env


# Install dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Run Prisma migrations during build (optional, can also be run at container start)
# RUN npx prisma migrate deploy

# Expose the backend port
EXPOSE 5000

# Command to start the backend
CMD ["npm", "run", "dev"]